LastSessions<|||>1<|||>
LastActiveSession<|||>1<|||>db_web_sekolah
ColWidths_connform.ListSessions<|||>1<|||>163,50,50,50,50,50,10
ColsVisible_connform.ListSessions<|||>1<|||>0,1,4,6
ColPositions_connform.ListSessions<|||>1<|||>0,1,2,3,4,5,6
ColSort_connform.ListSessions<|||>1<|||>0,0
ColWidths_frmTableEditor.listColumns<|||>1<|||>46,100,152,90,60,65,50,117,130,139,100,100
ColsVisible_frmTableEditor.listColumns<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11
ColPositions_frmTableEditor.listColumns<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11
ColSort_frmTableEditor.listColumns<|||>1<|||>-1,0
ColWidths_frmTableEditor.treeIndexes<|||>1<|||>234,100,80,120,80
ColsVisible_frmTableEditor.treeIndexes<|||>1<|||>0,1,2,3,4
ColPositions_frmTableEditor.treeIndexes<|||>1<|||>0,1,2,3,4
ColSort_frmTableEditor.treeIndexes<|||>1<|||>-1,0
ColWidths_frmTableEditor.listForeignKeys<|||>1<|||>200,80,100,80,80,80
ColsVisible_frmTableEditor.listForeignKeys<|||>1<|||>0,1,2,3,4,5
ColPositions_frmTableEditor.listForeignKeys<|||>1<|||>0,1,2,3,4,5
ColSort_frmTableEditor.listForeignKeys<|||>1<|||>-1,0
ColWidths_frmTableEditor.listCheckConstraints<|||>1<|||>200,420
ColsVisible_frmTableEditor.listCheckConstraints<|||>1<|||>0,1
ColPositions_frmTableEditor.listCheckConstraints<|||>1<|||>0,1
ColSort_frmTableEditor.listCheckConstraints<|||>1<|||>-1,0
MainWinOnMonitor<|||>3<|||>0
ColWidths_MainForm.ListDatabases<|||>1<|||>150,80,50,50,50,50,50,50,50,50,120
ColsVisible_MainForm.ListDatabases<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10
ColPositions_MainForm.ListDatabases<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10
ColSort_MainForm.ListDatabases<|||>1<|||>0,0
ColWidths_MainForm.ListVariables<|||>1<|||>160,200,316
ColsVisible_MainForm.ListVariables<|||>1<|||>0,1,2
ColPositions_MainForm.ListVariables<|||>1<|||>0,1,2
ColSort_MainForm.ListVariables<|||>1<|||>0,0
ColWidths_MainForm.ListStatus<|||>1<|||>160,316,100,100
ColsVisible_MainForm.ListStatus<|||>1<|||>0,1,2,3
ColPositions_MainForm.ListStatus<|||>1<|||>0,1,2,3
ColSort_MainForm.ListStatus<|||>1<|||>0,0
ColWidths_MainForm.ListProcesses<|||>1<|||>70,80,80,80,80,50,50,188
ColsVisible_MainForm.ListProcesses<|||>1<|||>0,1,2,3,4,5,6,7
ColPositions_MainForm.ListProcesses<|||>1<|||>0,1,2,3,4,5,6,7
ColSort_MainForm.ListProcesses<|||>1<|||>0,1
ColWidths_MainForm.ListCommandStats<|||>1<|||>120,100,100,100,256
ColsVisible_MainForm.ListCommandStats<|||>1<|||>0,1,2,3,4
ColPositions_MainForm.ListCommandStats<|||>1<|||>0,1,2,3,4
ColSort_MainForm.ListCommandStats<|||>1<|||>1,1
ColWidths_MainForm.ListTables<|||>1<|||>120,70,70,120,120,70,100,50,70,70,70,70,70,90,120,70,70,70,50
ColsVisible_MainForm.ListTables<|||>1<|||>0,1,2,3,4,5,6,18
ColPositions_MainForm.ListTables<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
ColSort_MainForm.ListTables<|||>1<|||>0,0
MainWinWidth<|||>3<|||>879
MainWinHeight<|||>3<|||>466
SessionManager_WindowHeight<|||>3<|||>489
SessionManager_WindowLeft<|||>3<|||>995
SessionManager_WindowTop<|||>3<|||>174
Servers\ai_analyst_enterprise\SessionCreated<|||>1<|||>2026-05-20 00:08:58
Servers\ai_analyst_enterprise\Host<|||>1<|||>127.0.0.1
Servers\ai_analyst_enterprise\WindowsAuth<|||>3<|||>0
Servers\ai_analyst_enterprise\CleartextPluginEnabled<|||>3<|||>0
Servers\ai_analyst_enterprise\User<|||>1<|||>root
Servers\ai_analyst_enterprise\Password<|||>1<|||>9
Servers\ai_analyst_enterprise\LoginPrompt<|||>3<|||>0
Servers\ai_analyst_enterprise\Port<|||>1<|||>3306
Servers\ai_analyst_enterprise\NetType<|||>3<|||>0
Servers\ai_analyst_enterprise\Compressed<|||>3<|||>0
Servers\ai_analyst_enterprise\LocalTimeZone<|||>3<|||>0
Servers\ai_analyst_enterprise\QueryTimeout<|||>3<|||>30
Servers\ai_analyst_enterprise\KeepAlive<|||>3<|||>20
Servers\ai_analyst_enterprise\FullTableStatus<|||>3<|||>1
Servers\ai_analyst_enterprise\Databases<|||>1<|||>
Servers\ai_analyst_enterprise\Library<|||>1<|||>libmariadb.dll
Servers\ai_analyst_enterprise\Comment<|||>1<|||>
Servers\ai_analyst_enterprise\StartupScriptFilename<|||>1<|||>
Servers\ai_analyst_enterprise\TreeBackground<|||>3<|||>536870911
Servers\ai_analyst_enterprise\SSHtunnelActive<|||>3<|||>0
Servers\ai_analyst_enterprise\SshExecutable<|||>1<|||>
Servers\ai_analyst_enterprise\SSHtunnelHost<|||>1<|||>
Servers\ai_analyst_enterprise\SSHtunnelHostPort<|||>3<|||>22
Servers\ai_analyst_enterprise\SSHtunnelUser<|||>1<|||>
Servers\ai_analyst_enterprise\SSHtunnelPassword<|||>1<|||>9
Servers\ai_analyst_enterprise\SSHtunnelTimeout<|||>3<|||>4
Servers\ai_analyst_enterprise\SSHtunnelPrivateKey<|||>1<|||>
Servers\ai_analyst_enterprise\SSHtunnelPort<|||>3<|||>3307
Servers\ai_analyst_enterprise\SSL_Active<|||>3<|||>0
Servers\ai_analyst_enterprise\SSL_Key<|||>1<|||>
Servers\ai_analyst_enterprise\SSL_Cert<|||>1<|||>
Servers\ai_analyst_enterprise\SSL_CA<|||>1<|||>
Servers\ai_analyst_enterprise\SSL_Cipher<|||>1<|||>
Servers\ai_analyst_enterprise\SSL_Verification<|||>3<|||>2
Servers\ai_analyst_enterprise\IgnoreDatabasePattern<|||>1<|||>
Servers\ai_analyst_enterprise\LogFileDdl<|||>3<|||>0
Servers\ai_analyst_enterprise\LogFileDml<|||>3<|||>0
Servers\ai_analyst_enterprise\LogFilePath<|||>1<|||>C:\Users\user\AppData\Roaming\HeidiSQL\Logs\%session\%db\%y%m%d.sql
Servers\db_smkn1_cilegon\SessionCreated<|||>1<|||>2026-05-21 20:46:18
Servers\db_smkn1_cilegon\Host<|||>1<|||>127.0.0.1
Servers\db_smkn1_cilegon\WindowsAuth<|||>3<|||>0
Servers\db_smkn1_cilegon\CleartextPluginEnabled<|||>3<|||>0
Servers\db_smkn1_cilegon\User<|||>1<|||>root
Servers\db_smkn1_cilegon\Password<|||>1<|||>9
Servers\db_smkn1_cilegon\LoginPrompt<|||>3<|||>0
Servers\db_smkn1_cilegon\Port<|||>1<|||>3306
Servers\db_smkn1_cilegon\NetType<|||>3<|||>0
Servers\db_smkn1_cilegon\Compressed<|||>3<|||>0
Servers\db_smkn1_cilegon\LocalTimeZone<|||>3<|||>0
Servers\db_smkn1_cilegon\QueryTimeout<|||>3<|||>30
Servers\db_smkn1_cilegon\KeepAlive<|||>3<|||>20
Servers\db_smkn1_cilegon\FullTableStatus<|||>3<|||>1
Servers\db_smkn1_cilegon\Databases<|||>1<|||>
Servers\db_smkn1_cilegon\Library<|||>1<|||>libmariadb.dll
Servers\db_smkn1_cilegon\Comment<|||>1<|||>
Servers\db_smkn1_cilegon\StartupScriptFilename<|||>1<|||>
Servers\db_smkn1_cilegon\TreeBackground<|||>3<|||>536870911
Servers\db_smkn1_cilegon\SSHtunnelActive<|||>3<|||>0
Servers\db_smkn1_cilegon\SshExecutable<|||>1<|||>
Servers\db_smkn1_cilegon\SSHtunnelHost<|||>1<|||>
Servers\db_smkn1_cilegon\SSHtunnelHostPort<|||>3<|||>22
Servers\db_smkn1_cilegon\SSHtunnelUser<|||>1<|||>
Servers\db_smkn1_cilegon\SSHtunnelPassword<|||>1<|||>7
Servers\db_smkn1_cilegon\SSHtunnelTimeout<|||>3<|||>4
Servers\db_smkn1_cilegon\SSHtunnelPrivateKey<|||>1<|||>
Servers\db_smkn1_cilegon\SSHtunnelPort<|||>3<|||>3307
Servers\db_smkn1_cilegon\SSL_Active<|||>3<|||>0
Servers\db_smkn1_cilegon\SSL_Key<|||>1<|||>
Servers\db_smkn1_cilegon\SSL_Cert<|||>1<|||>
Servers\db_smkn1_cilegon\SSL_CA<|||>1<|||>
Servers\db_smkn1_cilegon\SSL_Cipher<|||>1<|||>
Servers\db_smkn1_cilegon\SSL_Verification<|||>3<|||>2
Servers\db_smkn1_cilegon\IgnoreDatabasePattern<|||>1<|||>
Servers\db_smkn1_cilegon\LogFileDdl<|||>3<|||>0
Servers\db_smkn1_cilegon\LogFileDml<|||>3<|||>0
Servers\db_smkn1_cilegon\LogFilePath<|||>1<|||>C:\Users\user\AppData\Roaming\HeidiSQL\Logs\%session\%db\%y%m%d.sql
Servers\db_web_sekolah\SessionCreated<|||>1<|||>2026-05-18 23:25:10
Servers\db_web_sekolah\Host<|||>1<|||>127.0.0.1
Servers\db_web_sekolah\WindowsAuth<|||>3<|||>0
Servers\db_web_sekolah\CleartextPluginEnabled<|||>3<|||>0
Servers\db_web_sekolah\User<|||>1<|||>root
Servers\db_web_sekolah\Password<|||>1<|||>2
Servers\db_web_sekolah\LoginPrompt<|||>3<|||>0
Servers\db_web_sekolah\Port<|||>1<|||>3306
Servers\db_web_sekolah\NetType<|||>3<|||>0
Servers\db_web_sekolah\Compressed<|||>3<|||>0
Servers\db_web_sekolah\LocalTimeZone<|||>3<|||>0
Servers\db_web_sekolah\QueryTimeout<|||>3<|||>30
Servers\db_web_sekolah\KeepAlive<|||>3<|||>20
Servers\db_web_sekolah\FullTableStatus<|||>3<|||>1
Servers\db_web_sekolah\Databases<|||>1<|||>
Servers\db_web_sekolah\Library<|||>1<|||>libmariadb.dll
Servers\db_web_sekolah\Comment<|||>1<|||>
Servers\db_web_sekolah\StartupScriptFilename<|||>1<|||>
Servers\db_web_sekolah\TreeBackground<|||>3<|||>536870911
Servers\db_web_sekolah\SSHtunnelActive<|||>3<|||>0
Servers\db_web_sekolah\SshExecutable<|||>1<|||>
Servers\db_web_sekolah\SSHtunnelHost<|||>1<|||>
Servers\db_web_sekolah\SSHtunnelHostPort<|||>3<|||>22
Servers\db_web_sekolah\SSHtunnelUser<|||>1<|||>
Servers\db_web_sekolah\SSHtunnelPassword<|||>1<|||>4
Servers\db_web_sekolah\SSHtunnelTimeout<|||>3<|||>4
Servers\db_web_sekolah\SSHtunnelPrivateKey<|||>1<|||>
Servers\db_web_sekolah\SSHtunnelPort<|||>3<|||>3307
Servers\db_web_sekolah\SSL_Active<|||>3<|||>0
Servers\db_web_sekolah\SSL_Key<|||>1<|||>
Servers\db_web_sekolah\SSL_Cert<|||>1<|||>
Servers\db_web_sekolah\SSL_CA<|||>1<|||>
Servers\db_web_sekolah\SSL_Cipher<|||>1<|||>
Servers\db_web_sekolah\SSL_Verification<|||>3<|||>2
Servers\db_web_sekolah\IgnoreDatabasePattern<|||>1<|||>
Servers\db_web_sekolah\LogFileDdl<|||>3<|||>0
Servers\db_web_sekolah\LogFileDml<|||>3<|||>0
Servers\db_web_sekolah\LogFilePath<|||>1<|||>C:\Users\user\AppData\Roaming\HeidiSQL\Logs\%session\%db\%y%m%d.sql
Servers\db_web_sekolah\ServerVersionFull<|||>1<|||>8.4.3 - MySQL Community Server - GPL
Servers\db_web_sekolah\ConnectCount<|||>3<|||>1
Servers\db_web_sekolah\ServerVersion<|||>3<|||>80403
Servers\db_web_sekolah\LastConnect<|||>1<|||>2026-05-18 23:25:43
Servers\Laragon.MySQL\SessionCreated<|||>1<|||>2024-12-16 22:28:25
Servers\Laragon.MySQL\Host<|||>1<|||>127.0.0.1
Servers\Laragon.MySQL\WindowsAuth<|||>3<|||>0
Servers\Laragon.MySQL\CleartextPluginEnabled<|||>3<|||>0
Servers\Laragon.MySQL\User<|||>1<|||>root
Servers\Laragon.MySQL\Password<|||>1<|||>2
Servers\Laragon.MySQL\LoginPrompt<|||>3<|||>0
Servers\Laragon.MySQL\Port<|||>1<|||>3306
Servers\Laragon.MySQL\NetType<|||>3<|||>0
Servers\Laragon.MySQL\Compressed<|||>3<|||>0
Servers\Laragon.MySQL\LocalTimeZone<|||>3<|||>0
Servers\Laragon.MySQL\QueryTimeout<|||>3<|||>30
Servers\Laragon.MySQL\KeepAlive<|||>3<|||>20
Servers\Laragon.MySQL\FullTableStatus<|||>3<|||>1
Servers\Laragon.MySQL\Databases<|||>1<|||>
Servers\Laragon.MySQL\Library<|||>1<|||>libmariadb.dll
Servers\Laragon.MySQL\Comment<|||>1<|||>
Servers\Laragon.MySQL\StartupScriptFilename<|||>1<|||>
Servers\Laragon.MySQL\TreeBackground<|||>3<|||>536870911
Servers\Laragon.MySQL\SSHtunnelActive<|||>3<|||>0
Servers\Laragon.MySQL\SshExecutable<|||>1<|||>
Servers\Laragon.MySQL\SSHtunnelHost<|||>1<|||>
Servers\Laragon.MySQL\SSHtunnelHostPort<|||>3<|||>22
Servers\Laragon.MySQL\SSHtunnelUser<|||>1<|||>
Servers\Laragon.MySQL\SSHtunnelPassword<|||>1<|||>8
Servers\Laragon.MySQL\SSHtunnelTimeout<|||>3<|||>4
Servers\Laragon.MySQL\SSHtunnelPrivateKey<|||>1<|||>
Servers\Laragon.MySQL\SSHtunnelPort<|||>3<|||>3307
Servers\Laragon.MySQL\SSL_Active<|||>3<|||>0
Servers\Laragon.MySQL\SSL_Key<|||>1<|||>
Servers\Laragon.MySQL\SSL_Cert<|||>1<|||>
Servers\Laragon.MySQL\SSL_CA<|||>1<|||>
Servers\Laragon.MySQL\SSL_Cipher<|||>1<|||>
Servers\Laragon.MySQL\SSL_Verification<|||>3<|||>2
Servers\Laragon.MySQL\IgnoreDatabasePattern<|||>1<|||>
Servers\Laragon.MySQL\LogFileDdl<|||>3<|||>0
Servers\Laragon.MySQL\LogFileDml<|||>3<|||>0
Servers\Laragon.MySQL\LogFilePath<|||>1<|||>C:\Users\Leo\AppData\Roaming\HeidiSQL\Logs\%session\%db\%y%m%d.sql
Servers\Laragon.MySQL\ServerVersionFull<|||>1<|||>8.4.3 - MySQL Community Server - GPL
Servers\Laragon.MySQL\ConnectCount<|||>3<|||>1
Servers\Laragon.MySQL\ServerVersion<|||>3<|||>80403
Servers\Laragon.MySQL\LastConnect<|||>1<|||>2024-12-16 22:28:58
Servers\Laragon.MySQL\lastUsedDB<|||>1<|||>mysql
